steps:
  - name: Probo site setup
    plugin: Drupal
    makeFile: build-vies.make
    profileName: panopoly
    runInstall: true
    revertFeatures: true
  - name: Enabling demo module
    command: 'drush --root="/var/www/html" en vies_deploy -y'
  - name: Enable stage_file_proxy
    command: 'drush --root="/var/www/html" en stage_file_proxy -y'
    command: 'drush variable-set stage_file_proxy_origin "http://vies.dk"'
