steps:
  - name: Probo site setup
    plugin: Drupal
    makeFile: build-vies.make
    profileName: panopoly
    runInstall: true
    revertFeatures: true
  - name: Enabling demo module
    command: 'drush --root="/var/www/html" en vies_deploy -y'
